package eu.trentorise.game.model

rule "reward level-1"
when
    Action( id == 'taskCompleted')
    InputData(
    	$moves : data['moves'] == 5.0,
    	$errors : data['errors'] == 0.0
    )
    $pointsScore : PointConcept(name == "points")
    $goldCoinScore : PointConcept(name == "gold coins")
    $customData : CustomData(this["level"] == 'level-1')
then
	modify($pointsScore) { setScore(5.0); } // update the counter    
	modify($goldCoinScore) { setScore(3.0); } // update the counter
end


rule "reward level-2"
when
    Action( id == 'taskCompleted')
    InputData(
    	$moves : data['moves'] == 5.0,
    	$errors : data['errors'] == 0.0
    )
    $pointsScore : PointConcept(name == "points")
    $goldCoinScore : PointConcept(name == "gold coins")
    $customData : CustomData(this["level"] == 'level-2')
then
	double newPoints = $pointsScore.getScore() + 7.0;
	modify($pointsScore) { setScore(newPoints); } // update the counter
	double newGold = $goldCoinScore.getScore() + 3.0;    
	modify($goldCoinScore) { setScore(newGold); } // update the counter
end