package eu.trentorise.game.model
import eu.trentorise.game.core.Utility;

rule "consume a reward"
when
	Action ($id : id == "consume-reward")
	InputData ( $territoryConsume : data["territory"] != null, $cultureConsume : data["culture"] != null, $sportConsume : data["sport"] != null)
	$reward_territory : PointConcept( name == "reward_territory")
	$reward_culture : PointConcept( name == "reward_culture")
	$reward_sport : PointConcept( name == "reward_sport")
then
	double territoryRest = $reward_territory.getScore() - (double) $territoryConsume;
	double cultureRest = $reward_culture.getScore() - (double) $cultureConsume;
	double sportRest = $reward_sport.getScore() - (double) $sportConsume;
	if(territoryRest > 0 && cultureRest > 0 && sportRest > 0) {
		$reward_territory.setScore(territoryRest);
		$reward_culture.setScore(cultureRest);
		$reward_sport.setScore(sportRest);
		update($reward_territory);
		update($reward_culture);
		update($reward_sport);
	} else {
		utils.log("WARNING player doesn't have enough scores to consume the reward");
	}
end