package eu.trentorise.game.model


declare AlreadyLevelUp
end

// LEVEL 1

rule "level-1-errors-0"
when
	Action( id == 'taskCompleted')
    InputData(
    	$errors : data['errors'] == 0.0
    )
    $errorsScore : PointConcept(name == "errors")
    $customData : CustomData(this["level"] == null) // player without levels
    not AlreadyLevelUp()
then 
	modify($errorsScore) { setScore((double) $errors); } // update the counter
    modify($customData) { put("level", "level-1"); }
    insert(new AlreadyLevelUp());
end

rule "level-1-errors-1"
when
	Action( id == 'taskCompleted')
    InputData(
    	$errors : data['errors'] == 1.0
    )
    $errorsScore : PointConcept(name == "errors")
    $customData : CustomData(this["level"] == null) // player without levels
    not AlreadyLevelUp()
then
	modify($errorsScore) { setScore((double) $errors); } // update the counter
    modify($customData) { put("level", "level-1"); }
    insert(new AlreadyLevelUp());
end

rule "level-1-errors-2"
when
	Action( id == 'taskCompleted')
    InputData(
    	$errors : data['errors'] == 2.0
    )
    $errorsScore : PointConcept(name == "errors")
    $customData : CustomData(this["level"] == null) // player without levels
    not AlreadyLevelUp()
then
	modify($errorsScore) { setScore((double) $errors); } // update the counter
    modify($customData) { put("level", "level-1"); }
    insert(new AlreadyLevelUp());
end

rule "level-1-errors-great-equal-3"
when
	Action( id == 'taskCompleted')
    InputData(
    	$errors : data['errors'] >= 3.0
    )
    $errorsScore : PointConcept(name == "errors")
    $customData : CustomData(this["level"] == null) // player without levels
    not AlreadyLevelUp()
then
	modify($errorsScore) { setScore((double) $errors); } // update the counter
    modify($customData) { put("level", "level-1"); }
    insert(new AlreadyLevelUp());
end


// LEVEL 2

rule "level-2-errors-0"
when
	Action( id == 'taskCompleted')
    InputData(
    	$errors : data['errors'] == 0.0
    )
    $errorsScore : PointConcept(name == "errors")
    $customData : CustomData(this["level"] == "level-1")
    not AlreadyLevelUp()
then 
	modify($errorsScore) { setScore((double) $errors); } // update the counter
    modify($customData) { put("level", "level-2"); }
    insert(new AlreadyLevelUp());
end

rule "level-2-errors-1"
when
	Action( id == 'taskCompleted')
    InputData(
    	$errors : data['errors'] == 1.0
    )
    $errorsScore : PointConcept(name == "errors")
    $customData : CustomData(this["level"] == "level-1")
    not AlreadyLevelUp()
then
	modify($errorsScore) { setScore((double) $errors); } // update the counter
    modify($customData) { put("level", "level-2"); }
    insert(new AlreadyLevelUp());
end

rule "level-2-errors-2"
when
	Action( id == 'taskCompleted')
    InputData(
    	$errors : data['errors'] == 2.0
    )
    $errorsScore : PointConcept(name == "errors")
    $customData : CustomData(this["level"] == "level-1")
    not AlreadyLevelUp()
then
	modify($errorsScore) { setScore((double) $errors); } // update the counter
    modify($customData) { put("level", "level-2"); }
    insert(new AlreadyLevelUp());
end

rule "level-2-errors-great-equal-3"
when
	Action( id == 'taskCompleted')
    InputData(
    	$errors : data['errors'] >= 3.0
    )
    $errorsScore : PointConcept(name == "errors")
    $customData : CustomData(this["level"] == "level-1")
    not AlreadyLevelUp()
then
	modify($errorsScore) { setScore((double) $errors); } // update the counter
    modify($customData) { put("level", "level-2"); }
    insert(new AlreadyLevelUp());
end

// LEVEL 3

rule "level-3-errors-0"
when
	Action( id == 'taskCompleted')
    InputData(
    	$errors : data['errors'] == 0.0
    )
    $errorsScore : PointConcept(name == "errors")
    $customData : CustomData(this["level"] == "level-2")
    not AlreadyLevelUp()
then
	modify($errorsScore) { setScore((double) $errors); } // update the counter
    modify($customData) { put("level", "level-3"); }
    insert(new AlreadyLevelUp());
end

rule "level-3-errors-1"
when
	Action( id == 'taskCompleted')
    InputData(
    	$errors : data['errors'] == 1.0
    )
    $errorsScore : PointConcept(name == "errors")
    $customData : CustomData(this["level"] == "level-2")
    not AlreadyLevelUp()
then
	modify($errorsScore) { setScore((double) $errors); } // update the counter
    modify($customData) { put("level", "level-3"); }
    insert(new AlreadyLevelUp());
end

rule "level-3-errors-2"
when
	Action( id == 'taskCompleted')
    InputData(
    	$errors : data['errors'] == 2.0
    )
    $errorsScore : PointConcept(name == "errors")
    $customData : CustomData(this["level"] == "level-2")
    not AlreadyLevelUp()
then
	modify($errorsScore) { setScore((double) $errors); } // update the counter
    modify($customData) { put("level", "level-3"); }
    insert(new AlreadyLevelUp());
end

rule "level-3-errors-great-equal-3"
when
	Action( id == 'taskCompleted')
    InputData(
    	$errors : data['errors'] >= 3.0
    )
    $errorsScore : PointConcept(name == "errors")
    $customData : CustomData(this["level"] == "level-2")
    not AlreadyLevelUp()
then
	modify($errorsScore) { setScore((double) $errors); } // update the counter
    modify($customData) { put("level", "level-3"); }
    insert(new AlreadyLevelUp());
end

// LEVEL 4

rule "level-4-errors-0"
when
	Action( id == 'taskCompleted')
    InputData(
    	$errors : data['errors'] == 0.0
    )
    $errorsScore : PointConcept(name == "errors")
    $customData : CustomData(this["level"] == "level-3")
    not AlreadyLevelUp()
then
	modify($errorsScore) { setScore((double) $errors); } // update the counter
    modify($customData) { put("level", "level-4"); }
    insert(new AlreadyLevelUp());
end

rule "level-4-errors-1"
when
	Action( id == 'taskCompleted')
    InputData(
    	$errors : data['errors'] == 1.0
    )
    $errorsScore : PointConcept(name == "errors")
    $customData : CustomData(this["level"] == "level-3")
    not AlreadyLevelUp()
then
	modify($errorsScore) { setScore((double) $errors); } // update the counter
    modify($customData) { put("level", "level-4"); }
    insert(new AlreadyLevelUp());
end

rule "level-4-errors-2"
when
	Action( id == 'taskCompleted')
    InputData(
    	$errors : data['errors'] == 2.0
    )
    $errorsScore : PointConcept(name == "errors")
    $customData : CustomData(this["level"] == "level-3")
    not AlreadyLevelUp()
then
	modify($errorsScore) { setScore((double) $errors); } // update the counter
    modify($customData) { put("level", "level-4"); }
    insert(new AlreadyLevelUp());
end

rule "level-4-errors-great-equal-3"
when
	Action( id == 'taskCompleted')
    InputData(
    	$errors : data['errors'] >= 3.0
    )
    $errorsScore : PointConcept(name == "errors")
    $customData : CustomData(this["level"] == "level-3")
    not AlreadyLevelUp()
then
	modify($errorsScore) { setScore((double) $errors); } // update the counter
    modify($customData) { put("level", "level-4"); }
    insert(new AlreadyLevelUp());
end


// LEVEL 5

rule "level-5-errors-0"
when
	Action( id == 'taskCompleted')
    InputData(
    	$errors : data['errors'] == 0.0
    )
    $errorsScore : PointConcept(name == "errors")
    $customData : CustomData(this["level"] == "level-4")
    not AlreadyLevelUp()
then
	modify($errorsScore) { setScore((double) $errors); } // update the counter
    modify($customData) { put("level", "level-5"); }
    insert(new AlreadyLevelUp());
end

rule "level-5-errors-1"
when
	Action( id == 'taskCompleted')
    InputData(
    	$errors : data['errors'] == 1.0
    )
    $errorsScore : PointConcept(name == "errors")
    $customData : CustomData(this["level"] == "level-4")
    not AlreadyLevelUp()
then
	modify($errorsScore) { setScore((double) $errors); } // update the counter
    modify($customData) { put("level", "level-5"); }
    insert(new AlreadyLevelUp());
end

rule "level-5-errors-2"
when
	Action( id == 'taskCompleted')
    InputData(
    	$errors : data['errors'] == 2.0
    )
    $errorsScore : PointConcept(name == "errors")
    $customData : CustomData(this["level"] == "level-4")
    not AlreadyLevelUp()
then
	modify($errorsScore) { setScore((double) $errors); } // update the counter
    modify($customData) { put("level", "level-5"); }
    insert(new AlreadyLevelUp());
end

rule "level-5-errors-great-equal-3"
when
	Action( id == 'taskCompleted')
    InputData(
    	$errors : data['errors'] >= 3.0
    )
    $errorsScore : PointConcept(name == "errors")
    $customData : CustomData(this["level"] == "level-4")
    not AlreadyLevelUp()
then
	modify($errorsScore) { setScore((double) $errors); } // update the counter
    modify($customData) { put("level", "level-5"); }
    insert(new AlreadyLevelUp());
end

// LEVEL 6

rule "level-6-errors-0"
when
	Action( id == 'taskCompleted')
    InputData(
    	$errors : data['errors'] == 0.0
    )
    $errorsScore : PointConcept(name == "errors")
    $customData : CustomData(this["level"] == "level-5")
    not AlreadyLevelUp()
then
	modify($errorsScore) { setScore((double) $errors); } // update the counter
    modify($customData) { put("level", "level-6"); }
    insert(new AlreadyLevelUp());
end

rule "level-6-errors-1"
when
	Action( id == 'taskCompleted')
    InputData(
    	$errors : data['errors'] == 1.0
    )
    $errorsScore : PointConcept(name == "errors")
    $customData : CustomData(this["level"] == "level-5")
    not AlreadyLevelUp()
then
	modify($errorsScore) { setScore((double) $errors); } // update the counter
    modify($customData) { put("level", "level-6"); }
    insert(new AlreadyLevelUp());
end

rule "level-6-errors-2"
when
	Action( id == 'taskCompleted')
    InputData(
    	$errors : data['errors'] == 2.0
    )
    $errorsScore : PointConcept(name == "errors")
    $customData : CustomData(this["level"] == "level-5")
    not AlreadyLevelUp()
then
	modify($errorsScore) { setScore((double) $errors); } // update the counter
    modify($customData) { put("level", "level-6"); }
    insert(new AlreadyLevelUp());
end

rule "level-6-errors-great-equal-3"
when
	Action( id == 'taskCompleted')
    InputData(
    	$errors : data['errors'] >= 3.0
    )
    $errorsScore : PointConcept(name == "errors")
    $customData : CustomData(this["level"] == "level-5")
    not AlreadyLevelUp()
then
	modify($errorsScore) { setScore((double) $errors); } // update the counter
    modify($customData) { put("level", "level-6"); }
    insert(new AlreadyLevelUp());
end

// LEVEL 7

rule "level-7-errors-0"
when
	Action( id == 'taskCompleted')
    InputData(
    	$errors : data['errors'] == 0.0
    )
    $errorsScore : PointConcept(name == "errors")
    $customData : CustomData(this["level"] == "level-6")
    not AlreadyLevelUp()
then
	modify($errorsScore) { setScore((double) $errors); } // update the counter
    modify($customData) { put("level", "level-7"); }
    insert(new AlreadyLevelUp());
end

rule "level-7-errors-1"
when
	Action( id == 'taskCompleted')
    InputData(
    	$errors : data['errors'] == 1.0
    )
    $errorsScore : PointConcept(name == "errors")
    $customData : CustomData(this["level"] == "level-6")
    not AlreadyLevelUp()
then
	modify($errorsScore) { setScore((double) $errors); } // update the counter
    modify($customData) { put("level", "level-7"); }
    insert(new AlreadyLevelUp());
end

rule "level-7-errors-2"
when
	Action( id == 'taskCompleted')
    InputData(
    	$errors : data['errors'] == 2.0
    )
    $errorsScore : PointConcept(name == "errors")
    $customData : CustomData(this["level"] == "level-6")
    not AlreadyLevelUp()
then
	modify($errorsScore) { setScore((double) $errors); } // update the counter
    modify($customData) { put("level", "level-7"); }
    insert(new AlreadyLevelUp());
end

rule "level-7-errors-great-equal-3"
when
	Action( id == 'taskCompleted')
    InputData(
    	$errors : data['errors'] >= 3.0
    )
    $errorsScore : PointConcept(name == "errors")
    $customData : CustomData(this["level"] == "level-6")
    not AlreadyLevelUp()
then
	modify($errorsScore) { setScore((double) $errors); } // update the counter
    modify($customData) { put("level", "level-7"); }
    insert(new AlreadyLevelUp());
end


// LEVEL 8

rule "level-8-errors-0"
when
	Action( id == 'taskCompleted')
    InputData(
    	$errors : data['errors'] == 0.0
    )
    $errorsScore : PointConcept(name == "errors")
    $customData : CustomData(this["level"] == "level-7")
    not AlreadyLevelUp()
then
	modify($errorsScore) { setScore((double) $errors); } // update the counter
    modify($customData) { put("level", "level-8"); }
    insert(new AlreadyLevelUp());
end

rule "level-8-errors-1"
when
	Action( id == 'taskCompleted')
    InputData(
    	$errors : data['errors'] == 1.0
    )
    $errorsScore : PointConcept(name == "errors")
    $customData : CustomData(this["level"] == "level-7")
    not AlreadyLevelUp()
then
	modify($errorsScore) { setScore((double) $errors); } // update the counter
    modify($customData) { put("level", "level-8"); }
    insert(new AlreadyLevelUp());
end

rule "level-8-errors-2"
when
	Action( id == 'taskCompleted')
    InputData(
    	$errors : data['errors'] == 2.0
    )
    $errorsScore : PointConcept(name == "errors")
    $customData : CustomData(this["level"] == "level-7")
    not AlreadyLevelUp()
then
	modify($errorsScore) { setScore((double) $errors); } // update the counter
    modify($customData) { put("level", "level-8"); }
    insert(new AlreadyLevelUp());
end

rule "level-8-errors-3"
when
	Action( id == 'taskCompleted')
    InputData(
    	$errors : data['errors'] == 3.0
    )
    $errorsScore : PointConcept(name == "errors")
    $customData : CustomData(this["level"] == "level-7")
    not AlreadyLevelUp()
then
	modify($errorsScore) { setScore((double) $errors); } // update the counter
    modify($customData) { put("level", "level-8"); }
    insert(new AlreadyLevelUp());
end

rule "level-8-errors-4"
when
	Action( id == 'taskCompleted')
    InputData(
    	$errors : data['errors'] == 4.0
    )
    $errorsScore : PointConcept(name == "errors")
    $customData : CustomData(this["level"] == "level-7")
    not AlreadyLevelUp()
then
	modify($errorsScore) { setScore((double) $errors); } // update the counter
    modify($customData) { put("level", "level-8"); }
    insert(new AlreadyLevelUp());
end

rule "level-8-errors-great-equal-5"
when
	Action( id == 'taskCompleted')
    InputData(
    	$errors : data['errors'] >= 5.0
    )
    $errorsScore : PointConcept(name == "errors")
    $customData : CustomData(this["level"] == "level-7")
    not AlreadyLevelUp()
then
	modify($errorsScore) { setScore((double) $errors); } // update the counter
    modify($customData) { put("level", "level-8"); }
    insert(new AlreadyLevelUp());
end