package eu.trentorise.game.model
import java.lang.Math;


// LEVEL 1
rule "reward level-1-0errors"
salience -1000
when
    Action( id == 'taskCompleted')
    InputData(
    	$errors : data['errors'] == 0.0,
        $timeSpent : data['timeSpent'] 
    )
    $pointsScore : PointConcept(name == "points")
    $goldCoinScore : PointConcept(name == "gold coins")
    $customData : CustomData(this["level"] == 'level-1')
then
       int time = (int) $timeSpent;
	   double points = $pointsScore.getScore();
       double rewardPoints =   50.0 + ( 50.0 - Math.round(time/2.0));
       modify($pointsScore) { setScore(points+rewardPoints); } // update the counter    
       
       double goldcoins =  $goldCoinScore.getScore();
       double rewardGold = 2.0;
       if(time < 60){
         rewardGold = rewardGold+1.0;
       }
	   modify($goldCoinScore) { setScore(goldcoins+rewardGold); } // update the counter
end


// LEVEL 2
rule "reward level-2-0errors"
salience -1000
when
    Action( id == 'taskCompleted')
    InputData(
    	$errors : data['errors'] == 0.0,
        $timeSpent : data['timeSpent'] 
    )
    $pointsScore : PointConcept(name == "points")
    $goldCoinScore : PointConcept(name == "gold coins")
    $customData : CustomData(this["level"] == 'level-2')
then
       int time = (int) $timeSpent;
	   double points = $pointsScore.getScore();
       double rewardPoints =   70.0 + ( 70.0 - Math.round(time/2.0));
       modify($pointsScore) { setScore(points+rewardPoints); } // update the counter    
       
       double goldcoins =  $goldCoinScore.getScore();
       double rewardGold = 1.0;
       if(time < 30){
         rewardGold = rewardGold+1.0;
       }
	   modify($goldCoinScore) { setScore(goldcoins+rewardGold); } // update the counter
end