package eu.trentorise.game.model

import eu.trentorise.game.core.Utility;

global Utility utils;

rule 'ch_next_badge_check'
	salience -2000
when
	$challenge : ChallengeConcept( modelName == "nextBadge", 
	                               $target: fields["target"] != null, 
	                               $bonusPointType : fields["bonusPointType"], 
	                               $bonusScore : fields["bonusScore"], 
	                               $bcName : fields["badgeCollectionName"], 
	                               $counter: fields["initialBadgeNum"], 
	                               isCompleted() != true )
	BadgeCollectionConcept( name == $bcName, 
	                              $badges : badgeEarned, 
	                              badgeEarned.size() >= $target + $counter )
	$pc : PointConcept(name == (String) $bonusPointType)
then
	utils.log('nextBadge COMPLETED');
	$challenge.completed();
	double newScore = $pc.getScore() + (Double) $bonusScore;
	modify($pc) { setScore(newScore) };
	update($challenge);	
end
