package eu.trentorise.game.model

//list any import classes here.
import eu.trentorise.game.core.Utility;

//declare any global variables here
global Utility utils;

rule 'ch_percentageIncrement_check'
salience -2000
when
	$challenge : ChallengeConcept( modelName == "percentageIncrement", 
	                               $counter: fields["counterName"], 
	                               $target: fields["target"], 
	                               $periodName: fields["periodName"] , 
	                               $bonusPointType : fields["bonusPointType"], 
	                               $bonusScore : fields["bonusScore"], isCompleted() != true )
	PointConcept( name == (String) $counter, 
	              $score: score, 
	              getPeriodCurrentScore((String)$periodName) >= $target)
	$pc : PointConcept(name == (String) $bonusPointType)
then
	utils.log('percentageIncrement COMPLETED');
	$challenge.completed();
	if ($bonusScore instanceof Long) {
		 double newScore = $pc.getScore() + (Long) $bonusScore; 
	     modify($pc) { setScore(newScore) };
	} else if ($bonusScore instanceof Integer) {
	     double newScore = $pc.getScore() + (Integer) $bonusScore; 
	     modify($pc) { setScore(newScore) };
	} else {
	     double newScore = $pc.getScore() + (Double) $bonusScore; 
	     modify($pc) { setScore(newScore) };
	}
	update($challenge);
end
